# Generated by Django 3.2.8 on 2021-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('TweetId', models.AutoField(primary_key=True, serialize=False)),
                ('TweetContent', models.CharField(max_length=50)),
                ('TweetAuthor', models.CharField(max_length=40)),
            ],
        ),
    ]
